### PR TITLE
Release v2.0.0

### PR DESCRIPTION
**Pull request by lacework-releng**
# Release Notes
Another day, another release. These are the release notes for the version `v2.0.0`.

## Refactor
* refactor: update roles used for audit log storage bucket (#22) (Mike Laramie)([5db1abf](https://github.com/lacework/terraform-gcp-audit-log/commit/5db1abfb4122d84133a22b6400b9ba7c9aa47815))
## Other Changes
* chore: version bump to v1.0.2-dev (Lacework)([9a76f7d](https://github.com/lacework/terraform-gcp-audit-log/commit/9a76f7d8102682f412764320bc3bdc8eabe99a92))

### CODE REVIEW

**Review by afiune — CHANGES_REQUESTED** [review]
This refactor requires us to a major version bump!

I'll help with that

tenor-79001757

**Comment by mikelaramie** [comment]
Hey @afiune !  I just noticed this change hasn't made it into the upstream terraform registry yet (a tf destroy gcp run just failed for me due to the old permissions).  Do we have a timeline on this getting pushed?  Thanks!

**Comment by afiune** [comment]
@mikelaramie I've forgotten about this, apologies. I am taking care of it right now.

**Review by afiune — APPROVED** [review]
tenor-57500256

**Pull request merged**
